package golem-example:shipment;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-example-shipment-api {
  add: func(value: u64);
  get: func() -> u64;
}

world golem-example-shipment {
  export golem-example-shipment-api;
}
