package golem-example:shipment-service;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-example-shipment-service-api {
  use golem-example:shipment-exports/golem-example-shipment-api.{shipment};

  new-shipment: func() -> shipment;
}

world golem-example-shipment-service {
  export golem-example-shipment-service-api;
}
