package golem-example:order;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-example-order-api {
  add: func(value: u64);
  get: func() -> u64;
}

world golem-example-order {
  export golem-example-order-api;
}
