package golem-example:shipping;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-example-shipping-api {
  add: func(value: u64);
  get: func() -> u64;
}

world golem-example-shipping {
  export golem-example-shipping-api;
}
