package golem-example:billing;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-example-billing-api {
  add: func(value: u64);
  get: func() -> u64;
}

world golem-example-billing {
  export golem-example-billing-api;
}
