package golem-example:warehouse;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface golem-example-warehouse-api {
  add: func(value: u64);
  get: func() -> u64;
}

world golem-example-warehouse {
  export golem-example-warehouse-api;
}
